language: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    # install toolchains
    - g++-7
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
script:
  - g++-7 -v
  - grep CXX_COMPILER CMakeLists.txt
  - ./build.sh
